modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]
modId="the_vault"
version="${file.jarVersion}"
displayName="The Vault"
description='''
Iskallmod (very cool)'''
